### ISSUE TITLE
Inserting new lines with `height: auto` container does not scroll added line into view

### ISSUE THREAD

**Issue by artaommahe** [quilljs/quill#1361]
Quill does not handle autoscroll on new lines if container has `height: 100%` and window should be scrolled instead of container.

**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/NppeBv
2. Add many new lines

**Expected behavior**:
When new line added out of view Quill should autoscroll to it

**Actual behavior**:
New lines added out of view

**Version**: 1.2.2

**Comment by jhchen** [comment]
Autoscrolling involves a bit more setup unfortunately to work reliably across browsers. An example is [here](http://quilljs.com/playground/#autogrow-height).

**Comment by artaommahe** [comment]
@jhchen that example has same issue - place cursor at any line and press enter many times. New lines below viewport will not trigger autoscroll

**Comment by jhchen** [comment]
Yes you are right it seems to have broken since I last remember. Thanks for the report.

**Comment by jhchen** [comment]
The [autogrowing](http://quilljs.com/playground/#autogrow-height) example is now working so if you adjust your codepen similarly and use 1.2.3 it should now be resolved.

**Comment by artaommahe** [comment]
@jhchen still does not work with scroll on body
http://codepen.io/anon/pen/MpLBwo
```
scrollingContainer: 'body', 
```
version 1.2.3

**Comment by jhchen** [comment]
Now my previous comment that more setup is involved and that the autoscroll example should be helpful is accurate.

**Comment by artaommahe** [comment]
@jhchen what do mean by `more setup`? if i replace `scrollingContainer: '#scrolling-container'` with `body` in autogrowing example than autoscroll on new lines does not work. Does it mean that autoscroll for `body` should be handled somehow manually or what did i miss?

**Comment by jhchen** [comment]
There are relevant CSS rules in the example that are necessary

**Comment by dakmau** [comment]
@jhchen It looks like the issue that many people are having is that autoscroll is disabled if the editor, including #scrolling-container, is nested within another div element.

**Comment by artaommahe** [comment]
@dakmau just look at http://codepen.io/anon/pen/MpLBwo ...
