### ISSUE TITLE
Header 3-6 without icons

### ISSUE THREAD

**Issue by pke** [quilljs/quill#2206]
The toolbar does not render header 3-6 SVG assets although they are in the assets folder.
The problem is the lookup table for header icons (ui/icons.js)

```diff
'header': {
    '1'       : require('../assets/icons/header.svg'),
-   '2'       : require('../assets/icons/header-2.svg')
+   '2'       : require('../assets/icons/header-2.svg'),
+   '3'       : require('../assets/icons/header-3.svg'),
+   '4'       : require('../assets/icons/header-4.svg'),
+   '5'       : require('../assets/icons/header-5.svg'),
+   '6'       : require('../assets/icons/header-6.svg')
  },
```

Since I am on Windows I can not easily build a fork to test this out, but it should be easy to patch.

**Comment by pke** [comment]
Fixed in #2207

**Comment by jhchen** [comment]
Duplicate https://github.com/quilljs/quill/issues/1730

**Comment by dinukapj** [comment]
Still happens in 2.0.0.

Markup:

```
 <script>
     const toolbarOptions = [
         ['bold', 'italic', 'underline', 'strike'],
         ['blockquote', 'code-block'],
         ['link', 'image'],

         [{ 'header': 1 }, { 'header': 2 }, { 'header': 3 }, { 'header': 4 }],
         [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'list': 'check' }],
         [{ 'script': 'sub' }, { 'script': 'super' }]
     ];

     const quill = new Quill('#editor', {
         modules: {
             toolbar: toolbarOptions
         },
         placeholder: 'Compose module content',
         theme: 'snow'
     });
 </script>
```

![image](https://github.com/quilljs/quill/assets/11241826/57db167e-3b9d-4ad2-baf0-9285d0da7d06)
