### ISSUE TITLE
Latest Quill Release using deprecated DOMNodeInserted mutation event

### ISSUE THREAD

**Issue by highvoltz** [quilljs/quill#3806]
The latest quill release is using deprecated mutation event DOMNodeInserted that will be removed/disabled from Chrome around July 2024. See https://chromestatus.com/feature/5083947249172480

**Platforms**:

Chrome browser

**Version**:

1.3.7

**Comment by luin** [comment]
We are working on the 2.0 release which has already removed the use of mutation events.

**Comment by kathirr007** [comment]
> We are working on the 2.0 release which has already removed the use of mutation events.

Hi @luin is there any update on this? Any tendative date for the new release with this issue fixed.

Thank you so much in advance.

**Comment by c0ldst0rage** [comment]
Good luck with the revamp!

**Comment by LovaArutinovi** [comment]
I have this problem with v2.0.0

**Comment by millette** [comment]
@kathirr007 See https://github.com/quilljs/quill/milestone/2

**Comment by Bkumar48** [comment]
I'm facing this error. can anyone help me with fixing this? 
[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Comment by Li54nder** [comment]
Me also facing the same error now with "react-quill": "^2.0.0":
[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.
Any update on this?

**Comment by juanr941** [comment]
I am also facing this issue, any updates. Many thanks team for your hard work

**Comment by erinknowles0501** [comment]
@luin Do you know if the changes implemented for this issue in Version 2 will be breaking changes? I ask because we use a library that uses Quill (Vue2-editor) and they haven't responded to my question about their upgrade plan/timeline.

**Comment by luin** [comment]
@erinknowles0501 It's an internal change so I don't expect any breaking changes introduced by it. Having said that, v2 does include some other breaking changes.

**Comment by EdManukyan** [comment]
@luin do you have any updates on this?

> We are working on the 2.0 release which has already removed the use of mutation events.

**Comment by luin** [comment]
@EdManukyan We've already released 2.0.0-beta.0 and it's feature-complete. We are looking for feedbacks from the community before a stable release.

**Comment by EdManukyan** [comment]
@luin thanks for the quick response, any date prediction on stable release ?

**Comment by mjwweb** [comment]
@luin The only 2.0.0-beta.0 I found was for React. I installed the latest version for vanilla js from [here](https://www.npmjs.com/package/quill2).

I still get the DOMNodeInserted mutation warning. Is there a version out for vanilla js that doesn't have this issue? Thanks

**Comment by luin** [comment]
@mjwweb The package link that you provided is not the official package. You can install the beta version with `npm install quill@beta".

**Comment by BowaDAO** [comment]
Any update because I am still getting the warning also.  or do you suggest we go with the beta version for now? I see you mentioned something about the beta version.

**Comment by mfreed7** [comment]
> @luin Thanks for your reply, I have another question - when DOMNodeInserted is removed from browsers, will Version 1 still work to some extent?

Hi, I'd love to know the answer to this question also! FYI, you can test in Chrome by going to `chrome://flags/#mutation-events` and selecting "Disabled". Then restart the browser. That will make all Mutation Events (including `DOMNodeInserted`) not do anything, as they will in July by default. Would someone be able to verify that this still works with a pre-2.0 QuillJS? In my own testing, v1.0 seems to work fine for normal operations, even without Mutation Events functioning. But it's definitely possible I missed something.

Side note, please see https://developer.chrome.com/blog/mutation-events-deprecation for more details about this removal. In my analysis, it turns out QuillJS is **the top cause** of usage of Mutation Events across the web. It'd be great to know whether their removal will be a breaking change or not. I really appreciate that they've been removed from v2.0. Good luck with that launch.

**Comment by EdManukyan** [comment]
@luin anything about the comment above ?

**Comment by AKKHILESHRP** [comment]
[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

I'm facing this error while working in Quill. Please help me with this guys

**Comment by superuntitled** [comment]
Google's current plan is to remove mutation events in Chrome 127 which will be stable on July 30, 2024. Does this mean that will no longer work?
https://developer.chrome.com/blog/mutation-events-deprecation

**Comment by luin** [comment]
Hi all 👋

We just released Quill 2.0.0-rc.0, which has already been modernized and doesn't use the deprecated APIs anymore. It's recommended to upgrade from 1.x.x to that version. You can find the documentation and migration guide on https://v2.quilljs.com/ and please also feel free to let me know if you encounter any issues.

We plan to release 2.0.0 on March 1st if anyone prefers to a stable version.

**Comment by igortrinidad** [comment]
What a great news! Congratulations for the hard work guys 🚀👏

**Comment by EdManukyan** [comment]
@luin i know maybe this is not the question for here but the suggestion will be appreciated. So i have upgraded to v2.0(thx for the work), but i have one issue so my code is...
`const Embed = Quill.import('blots/embed');
export class EditorAssetBlot extends Embed implements EditorBlotInterface {
  static blotName = 'editorAsset';
  static tagName = 'editor-asset';
`  
and i have this error:
`TS2345: Argument of type  typeof EditorAssetBlot  is not assignable to parameter of type
string | BlotConstructor | Attributor | Record<string, unknown>
Type  typeof EditorAssetBlot  is not assignable to type  BlotConstructor 
Type  EditorAssetBlot  is missing the following properties from type  Blot :  scroll, parent, prev, next , and  17  more`

**Comment by brunowbbs** [comment]
Hello, I'm using version 2.0 of react quill, but the warning message keeps appearing.

**Comment by Sivakumar0703** [comment]
I'm using react-quill V2 and i got warning from chrome . can anyone help me how to solve this.


 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Comment by luin** [comment]
@Sivakumar0703 We'd love to offer helps for the react-quill project to upgrade to Quill v2 but haven't seen any signals the project would accept PRs for that. Before react-quill gets upgraded, you can refer to https://quilljs.com/playground/react to see how you can use Quill in a React project without any third-party libraries.

**Comment by adgoncal** [comment]
@luin the playground example is helpful, but it would be really nice to have examples in typescript as well. 
Also, Quill v2 is written in typescript, but you are not exposing some of the types, such as `Options` and `ExpandedOptions`. This makes it difficult to create a wrapper component around Quill with proper type checking.

**Comment by Sivakumar0703** [comment]
> @Sivakumar0703 We'd love to offer helps for the react-quill project to upgrade to Quill v2 but haven't seen any signals the project would accept PRs for that. Before react-quill gets upgraded, you can refer to https://quilljs.com/playground/react to see how you can use Quill in a React project without any third-party libraries.

thank you. i have switched from react-quill to quill and everything is ok now. could you tell me how handle images when using quill toolbar because when i click on image icon a prompt is opened for entering the image url.

**Comment by Sivakumar0703** [comment]
> @Sivakumar0703 I am also using Quill in React and I just switched from using react-quill to just Quill. The example in the playground is useful but might be hard to read with all the extra features displayed.
> 
> Here is a very simplified version of how I implemented it. We must now use useRef to manually create a reference to a DOM element and then manage the lifecycle by initialising Quill in a useEffect hook.
> 
> Rendering Quill editor from the parent component: `<QuillEditor passText={setText} placeholder={placeholder} />`
> 
> In my quill component:
> 
> ```
> import React, { useEffect, useRef } from 'react';
> import Quill from 'quill';
> 
> const QuillEditor = ({ passText, placeholder }) => {
> 
> 	const editorRef = useRef(null);
> 
> 	useEffect(() => {
> 		const quill = new Quill(editorRef.current, {
> 			theme: 'snow',
> 			modules: {
> 				toolbar: [
> 					['bold', 'italic', 'underline', 'strike'],
> 					// Other options...
> 				],
> 			},
> 		});
> 		// Detect changes
> 		quill.on('text-change', () => {
> 			let content = quill.root.innerHTML;
> 			passText(content);
> 		});
> 		return () => {
> 			quill.off('text-change');
> 		};
> 	}, [passText, placeholder]);
>  
> 	// Rendering the QuillEditor component with a reference to the DOM element
> 	return <div ref={editorRef} />;
> };
> 
> export default QuillEditor;
> ```
> 
> Be ready for some changes. If you are using ordered lists and bullet lists in your Quill editor, I have a CSS hack to overcome the fact that the new version of Quill wraps every lists in `<ol>` tags.

Thank you. Your ref helped me a lot.

**Comment by luin** [comment]
@adgoncal Will exporting `Options`. What the use case for `ExpandedOptions` since it's supposed to be used internally?

**Comment by adgoncal** [comment]
@luin thank you! If `ExpandedOptions` is only used internally, then there's no reason to export it. I only mentioned it because `Options` was not, and I was looking for alternatives.

**Comment by anye1tovar** [comment]
@luin, I installed the latest version of Quill (`npm install quill@2.0.0-rc.4`) in React TypeScript + Vite. The warning disappeared, but the Editor didn't set the default text value that I had predefined. I had to uninstall this version and revert to version 1.3.7 that I had before.

I'm also using PrimeReact and importing the component as `import { Editor } from 'primereact/editor';` Do you know if it might be due to a PrimeReact error?

If any of you have a solution for this issue using an updated version, I'm all ears and would be very grateful.

Thanks for your hard work! :)

**Comment by adgoncal** [comment]
@anye1tovar 
> I'm also using PrimeReact and importing the component as `import { Editor } from 'primereact/editor';` Do you know if it might be due to a PrimeReact error?
> 
> If any of you have a solution for this issue using an updated version, I'm all ears and would be very grateful.

A quick search on primereact's issues show they do not yet support Quill 2. They're waiting for the official release: https://github.com/primefaces/primereact/issues/5960

**Comment by pacozevallos** [comment]
> @luin, I installed the latest version of Quill (`npm install quill@2.0.0-rc.4`) in React TypeScript + Vite. The warning disappeared, but the Editor didn't set the default text value that I had predefined. I had to uninstall this version and revert to version 1.3.7 that I had before.
> 
> I'm also using PrimeReact and importing the component as `import { Editor } from 'primereact/editor';` Do you know if it might be due to a PrimeReact error?
> 
> If any of you have a solution for this issue using an updated version, I'm all ears and would be very grateful.
> 
> Thanks for your hard work! :)

Hello, did you find a solution? I have a similar problem with Angular 17.1.2, PrimeNg 17.13, quill@2.0.0-rc.5 I am using a reactive form and it does not recognize the default value of a "formControlName". I tried downgrading the version to quill@1.3.7 and it works but I get the warning.

Any help is welcome.

**Comment by hoangbuu1510** [comment]
There is no quill 2.0 update for vue 3 yet, right?

**Comment by ahelmi365** [comment]
> @brunowbbs react-quill 2.0 uses quill 1.3. You can actually use Quill in your React project directly without react-quill: https://quilljs.com/playground/react

When I try to use quill in my react project created by Vite + TypeScript, I got a lot of errors. Can you please share a version works with TypeScript?

**Comment by hugopqt** [comment]
Yes so same issue here, I use "react-quill": "^2.0.0" in my react app, and in the browser I receive "quill.js:4233 [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. This event type is deprecated, and will be removed from this browser VERY soon. Usage of this event listener will cause performance issues today, and represents a large risk of imminent site breakage. Consider using MutationObserver instead. See https://chromestatus.com/feature/5083947249172480 for more information." I was hoping it would be fix it in 2.0.0 but still I receive this warning, knowing that there wont be mutation events in Chrome 127 (going stable on July 30 2024) it seems like a big issue for us, any fix coming in the next weeks?

**Comment by luin** [comment]
Going to lock this conversation as the issue has been fixed in Quill 2.0. For people that come here due to the warning:

1. The warning only exists in Quill 1.x and has been fixed in Quill 2.0. Upgrading to Quill 2.0 should fix it.
2. `react-quill` is a third-party library. `react-quill` v2 uses Quill v1. You can use Quill 2.0 without a library. Here's an example: https://quilljs.com/playground/react.
3. If you are looking for an example using Quill v2 in a real project, here's an example: https://github.com/quilljs/webpack-example/tree/main.
4. I haven't tested but Quill 1.x should still work after the event type is removed from the browser. Although it's still recommended to upgrade to Quill 2.0.

Please feel free to create a new ticket if you find new issues.
