### ISSUE TITLE
[bug]Table parse issue

### ISSUE THREAD

**Issue by newproplus** [quilljs/quill#4023]
I paste the following table to quill in my project or https://quilljs.com/ , all the cells in thead will merged to one cell.

|  thead1   | thead2  |
|  ----  | ----  |
| cell1-1  | cell2-1 |
| cell1-2  | cell2-2 |

**Steps for Reproduction**

1. Copy the table
2. paste to quill2

**Expected behavior**:

Render the table as it.

**Actual behavior**:

All the cells in thead will merged to one cell, like (the 2nd thead doesn't shows):

|  thead1  thead2  ||
|  ----  | ----  |
| cell1-1  | cell2-1 |
| cell1-2  | cell2-2 |

**Platforms**:

Debian 12

Firefox 123.0

Google Chrome  122.0.6261.69

**Version**:

quill v2.0.0-rc.2

**Comment by Johansenlbw** [comment]
+1

**Comment by reinaldocoelho** [comment]
+1

**Comment by chienweiluo** [comment]
+1

**Comment by reinaldocoelho** [comment]
Hi, @newproplus!

 The issue was solved?
What's the final situation?

**Comment by newproplus** [comment]
@reinaldocoelho Actually, it hasn't been fixed properly. Since I submitted it for several months and no one replied, I have given up using it.

**Comment by atihonovschi** [comment]
Not fixed. The same behavior. The `<th>` elements are just converted into a single `<td>` instead, inside of a `<tbody>` instead of `<thead>`
