### ISSUE TITLE
Link tooltip sometimes renders outside of the editor

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#764]
Depending on the location of the highlighted text you are adding a link to, the link tooltip sometimes renders outside of the editor container.

This creates issues when the editor is embedded inside a large application, rendering the image tooltip sometimes unviewable.

Ideally the tooltip would leverage a location strategy similar to what the previous version of multi-cursor did: understand where it's being rendered in the bounds of the editor and left, right, or bottom-align as necessary.

**Steps for Reproduction**

![example tooltip](https://cloud.githubusercontent.com/assets/192650/16250602/7d32b458-37d3-11e6-9082-2080f8717a11.png)

**Expected behavior**:
Link tooltip renders within editor container

**Actual behavior**:
Link tooltip renders outside of editor container

**Platforms**:
Chrome 51 on Mac 10.11

**Version**:
Quill 1.0 Beta 6

**Comment by sachinrekhi** [comment]
FYI, this appears to be a regression from Quill 0.20.1

**Comment by jhchen** [comment]
You can use the `bounds` [configuration option](http://beta.quilljs.com/docs/configuration/#bounds) to control this. For technical reasons it's limited to left and right boundaries at the moment.

**Comment by sachinrekhi** [comment]
Oh great. I missed that configuration option. Just applied it. Immediately fixed the left boundary issue. But still seems to have an issue on the right boundary:

![right_margin](https://cloud.githubusercontent.com/assets/192650/16254091/6a3045be-37f1-11e6-81b5-e9031fe603fb.png)

**Comment by Toktik** [comment]
I can confirm right boundary issue,

**Comment by jhchen** [comment]
The right overflow should be fixed in the latest 1.0 branch. Can you confirm? For vertical overflow there's are css classes added that by default hides (with visibility, not display) the tooltip.

**Comment by sachinrekhi** [comment]
Right overflow issue still exists for me in Quill 1.0 Beta 9:

![screen shot 2016-07-18 at 8 05 53 pm](https://cloud.githubusercontent.com/assets/192650/16937370/2519b090-4d23-11e6-9543-b6bf2f785f1f.png)

**Comment by jhchen** [comment]
What's the structure of the editor containers looks like and their z-indexes and which one is the `bounds` set to? A simple [example](http://codepen.io/quill/pen/zBRRaQ) is working for me.

<img width="179" alt="screenshot 2016-07-18 21 00 48" src="https://cloud.githubusercontent.com/assets/192974/16938283/e07a1fe4-4d2a-11e6-9368-bbd70195ef72.png">

**Comment by sachinrekhi** [comment]
Aah yes, looks like it was a specific issue with my setup where the scrollbar was overlapping the tooltip, but the tooltip is in-fact within bounds. Was able to workaround my specific issue. So looks fixed then.
